# Copyright (C) Viktor Szakats. See LICENSE.md
# SPDX-License-Identifier: MIT

version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    cooldown:
      default-days: 7
    groups:
      gha-dependencies:
        patterns:
          - '*'
    schedule:
      interval: 'yearly'

  - package-ecosystem: 'pip'
    directory: '/.github/scripts'
    cooldown:
      default-days: 7
      semver-major-days: 15
      semver-minor-days: 7
      semver-patch-days: 3
    groups:
      pip-dependencies:
        patterns:
          - '*'
    schedule:
      interval: 'yearly'
