# Copyright (C) Daniel Stenberg, <daniel@haxx.se>, et al.
#
# SPDX-License-Identifier: curl

[default]
extend-ignore-identifiers-re = [
  "(connnection|EXAMPL|LISTings|ND|OBSOLET|RTO)",
  "^(Aas|eyeballers|gost|HELO|Linz|MAK|mak|nd|Tru64|typ|UE)$",
  "secur32",
]

[files]
extend-exclude = [
  ".github/scripts/codespell-ignore.words",
  ".github/scripts/spellcheck.words",
  "dev/explainopts.t",
  "docs/_companies.html",
  "_changes.html",
  "rfc/*.txt",
  "rfc/cookie_spec.html",
  "rfc/ntlm.html",
  "**/*.svg",
  "**/*.png",
]
