# Copyright (C) Daniel Stenberg, <daniel@haxx.se>, et al.
#
# SPDX-License-Identifier: curl

name: perlcheck

'on':
  push:
    branches:
      - master
      - '*/ci'
  pull_request:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

permissions: {}

jobs:
  perlcheck:
    name: 'perlcheck'
    runs-on: ubuntu-slim
    steps:
      - name: install prereqs
        run: sudo apt-get -o Dpkg::Use-Pty=0 install libcgi-pm-perl libstring-crc32-perl

      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false

      - name: perlcheck
        run: make perlcheck
