# Copyright (C) Daniel Stenberg, <daniel@haxx.se>, et al.
#
# SPDX-License-Identifier: curl

name: spell
on:
  push:
    branches:
      - master
    paths:
      - '*.md'
      - '*/*.md'
      - '**/requirements*'
      - '**/spellcheck.yml'
      - '**/spellcheck.yaml'
      - '**/wordlist.txt'
  pull_request:
    branches:
      - master
    paths:
      - '*.md'
      - '*/*.md'
      - '**/requirements*'
      - '**/spellcheck.yml'
      - '**/spellcheck.yaml'
      - '**/wordlist.txt'

permissions: {}

jobs:
  pyspelling:
    name: 'pyspelling'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
        with:
          persist-credentials: false

      - name: strip "uncheckable" sections from .md pages
        run: find docs -name "*.md" | xargs -t -n1 ./.github/scripts/cleanspell.pl

      - name: 'install'
        run: |
          sudo rm -f /etc/apt/sources.list.d/microsoft-prod.list
          sudo apt-get -o Dpkg::Use-Pty=0 update
          sudo rm -f /var/lib/man-db/auto-update
          sudo apt-get -o Dpkg::Use-Pty=0 install aspell aspell-en
          python3 -m venv ~/venv
          ~/venv/bin/pip --disable-pip-version-check --no-input --no-cache-dir install --progress-bar off --prefer-binary -r .github/scripts/requirements-docs.txt

      - name: 'check spelling'
        run: |
          source ~/venv/bin/activate
          # setup the custom wordlist
          grep -v '^#' .github/scripts/spellcheck.words > wordlist.txt
          aspell --version
          pyspelling --version
          pyspelling --verbose --jobs 5 --config .github/scripts/spellcheck.yaml
