# Copyright (C) Daniel Stenberg, <daniel@haxx.se>, et al.
#
# SPDX-License-Identifier: curl

name: spell
on:
  push:
    branches:
    - master
    paths:
    - '**.md'
    - '**/spellcheck.yml'
    - '**/spellcheck.yaml'
    - '**/wordlist.txt'
  pull_request:
    branches:
    - master
    paths:
    - '**.md'
    - '**/spellcheck.yml'
    - '**/spellcheck.yaml'
    - '**/wordlist.txt'

permissions: {}

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: strip "uncheckable" sections from .md pages
      run: find docs -name "*.md" | xargs -t -n1 ./.github/scripts/cleanspell.pl

    - name: setup the custom wordlist
      run: grep -v '^#' .github/scripts/spellcheck.words >  wordlist.txt

    - name: Check Spelling
      uses: rojopolis/spellcheck-github-actions@v0
      with:
        config_path: .github/scripts/spellcheck.yaml
